- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/pages/_dashboard.scss
- app/views/employee/dashboards/show.html.erb
> Transactions form

- app/assets/stylesheets/pages/_dashboard.scss
- app/controllers/employee/transactions_controller.rb
- app/views/employee/transactions/index.html.erb
- app/views/employee/transactions/new.html.erb
> simple form done

- app/assets/stylesheets/application.scss
- app/javascript/packs/application.js
- app/javascript/plugins/flatpickr.js
- app/views/employee/transactions/new.html.erb
- package.json
- yarn.lock
> add flatpicker

- app/javascript/controllers/form_controller.js
- app/views/shared/_navbar_mobile.html.erb
> adds transaction creation user journey

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/pages/_article.scss
- app/assets/stylesheets/pages/_index.scss
- app/controllers/employee/transactions_controller.rb
- app/views/articles/index.html.erb
- app/views/articles/show.html.erb
- db/seeds.rb
Linked all the cards and redirected to article show
> Create show article

- app/views/discussions/index.html.erb
- db/schema.rb
- db/seeds.rb
Discussion#index solved! Merci Cécile Backend
> Index discussion solve

- app/assets/stylesheets/components/_card.scss
- app/views/articles/index.html.erb
- app/views/employee/transactions/index.html.erb
- db/seeds.rb
> Transaction index

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_devicedisplay.scss
- app/controllers/application_controller.rb
- app/views/devise/registrations/new.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_avatar.html.erb
> add avatar to mobile

- app/views/articles/index.html.erb
- db/seeds.rb
1. Enhanced seed article content
2. Sur les cards articles --> aperçu des 100 premiers charactères
> peaufiner le content article

- app/views/articles/index.html.erb
- app/views/discussions/index.html.erb
- app/views/employee/transactions/index.html.erb
> fix titles format

- app/views/employee/transactions/index.html.erb
- db/seeds.rb
1. Enhance seed --> all in French // Added comments
2. Transacation index --> add PDF icon, dynamic comments
> index historique

- app/assets/stylesheets/pages/_discussion.scss
- app/views/discussions/index.html.erb
- app/views/discussions/show.html.erb
Content:
Modifs on the Discussion#index! Clean and convo cards fully links to specific chat
> Frontend chat

- app/views/shared/_navbar_mobile.html.erb
> home button

- db/seeds.rb
> seed modif

- app/views/employee/transactions/new.html.erb
> add full amount in new form

- app/assets/stylesheets/components/_navbar_mobile.scss
- app/controllers/employee/dashboards_controller.rb
- app/controllers/employee/transactions_controller.rb
- app/models/user.rb
- app/policies/transaction_policy.rb
- app/views/employee/dashboards/show.html.erb
- db/migrate/20210301130038_add_allow_new_transaction_to_users.rb
- db/migrate/20210301140305_remove_allow_new_transaction_from_users.rb
- db/schema.rb
> add block second transaction in same month

- app/assets/stylesheets/components/_slider.scss
- app/models/user.rb
- app/views/employee/transactions/new.html.erb
> new custom slider

- app/controllers/employee/transactions_controller.rb
- app/views/employee/transactions/show.html.erb
> bank account attachment in transaction creation

- app/assets/stylesheets/components/_card_article.scss
- app/assets/stylesheets/pages/_article.scss
- app/views/articles/show.html.erb
> justify text in index and show of articles

- app/views/devise/shared/_links.html.erb
- app/views/employee/transactions/index.html.erb
- app/views/employee/transactions/show.html.erb
PDF are linked on icons and open in a new tab
> pdf link and target

- db/schema.rb
- db/seeds.rb
> Create users in seed

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/pages/_hr_dashboard.scss
- app/assets/stylesheets/pages/_index.scss
- app/controllers/hr/dashboards_controller.rb
- app/javascript/packs/application.js
- app/views/hr/dashboards/show.html.erb
- package.json
- yarn.lock
1. Start display of RH dashboard
2. Installed gems for graphes
3. Initialized constants for controller-RH
> rh dashboard

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_sidebar.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/pages/_hr_dashboard.scss
- app/controllers/hr/dashboards_controller.rb
- app/views/hr/dashboards/show.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_sidebar.html.erb
> New feature 2

- app/assets/stylesheets/pages/_hr_dashboard.scss
- app/controllers/hr/dashboards_controller.rb
- app/views/hr/dashboards/show.html.erb
- db/schema.rb
> dashboard back

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/pages/_hr_dashboard.scss
- app/controllers/hr/base_controller.rb
- app/views/hr/dashboards/show.html.erb
- app/views/layouts/application.html.erb
> added charts on dashboard

- app/views/hr/dashboards/show.html.erb
> add green to dashboard and change scope

- app/assets/stylesheets/pages/_profile.scss
- app/views/pages/profile.html.erb
> fix layout problem in profile view

- app/views/employee/transactions/new.html.erb
- db/seeds.rb
> fixed typo in seed and deleted confirmation logo

- app/assets/stylesheets/components/_card_article.scss
- app/views/articles/index.html.erb
> change hover article category

- app/assets/stylesheets/pages/_discussion.scss
- app/javascript/controllers/alert_controller.js
- app/views/discussions/index.html.erb
Changed flex-grow: from 1 to 0.8 for hr discussions board
Title Discussions inline w/ other pages
> Flex grow hr

- app/views/articles/index.html.erb
- db/seeds.rb
1. Change seed for Nico number
2. Change container margin bottom in article
> seed and container

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_navbar_mobile.scss
- app/views/devise/sessions/new.html.erb
- app/views/shared/_navbar_mobile.html.erb
> fix buttons in login
